bankaccount:
	gcc -O2 -o app bankaccount.c -lpthread
fork:
	gcc -O2 -o app fork.c -lpthread
matmulseq:
	gcc -O2 -o app matmulseq.c -lpthread
msgqrecv:
	gcc -O2 -o recv msgqrecv.c -lpthread
msgqsend:
	gcc -O2 -o app msgqsend.c -lpthread
pthreadcreate:
	gcc -O2 -o app pthreadcreate.c -lpthread
pthreadcreate2:
	gcc -O2 -o app pthreadcreate2.c -lpthread
pthreadcreate3:
	gcc -O2 -o app pthreadcreate3.c -lpthread
semaphore:
	gcc -O2 -o app semaphore.c -lpthread
shmem:
	gcc -O2 -o app shmem.c -lpthread
shmem_task3:
	gcc -O2 -o app shmem_task3.c -lpthread
diningprofessors:
	gcc -O2 -o app diningprofessors.c -lpthread
lockfree:
	gcc -O2 -o app diningprofessors_deadlockfree.c -lpthread
run:
	./app
