all:
	gcc -O2 -o app bankaccount.c fork.c matmulseq.c msgqrecv.c msgqsend.c pthreadcreate.c pthreadcreate2.c pthreadcreate3.c qsortseq.c semaphore.c shmem.c -lpthread

one:
	gcc -O2 -o app shmem-Copy.c -lpthread

run:
	./app
