test1:
	gcc -O2 -o app test1.c -lpthread

test2:
	gcc -O2 -o app test2.c -lpthread

fifo:
	gcc -O2 -o app FIFO.c

lru:
	gcc -O2 -o app LRU.c

optimal:
	gcc -O2 -o app OPTIMAL.c

run:
	./app 4 256 mp3d.mem

sun:
	./app 64 512 mp3d.mem


# cd /mnt/c/Users/lukas/Downloads/Assignments/VT22/OS/DV1629/lab2_code_students
